server:
  port: 8081

spring:
  application:
    name: user-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/nexus_user_db
      auto-index-creation: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always